In [59]:
#Import pandas
import pandas as pd

In [60]:
#read CSV file
netflixdata=pd.read_csv("Netflix.csv")

In [61]:
#create dataframe
df=pd.DataFrame(netflixdata)

In [62]:
#Data preview 
df.head()

,Title,Genre,Tags,Languages,Series or Movie,Hidden Gem Score,Country Availability,Runtime,Director,Writer,...,Netflix Release Date,Production House,Netflix Link,IMDb Link,Summary,IMDb Votes,Image,Poster,TMDb Trailer,Trailer Site
0,Lets Fight Ghost,"Crime, Drama, Fantasy, Horror, Romance","Comedy Programmes,Romantic TV Comedies,Horror ...","Swedish, Spanish",Series,4.3,Thailand,< 30 minutes,Tomas Alfredson,John Ajvide Lindqvist,...,2021-03-04,"Canal+, Sandrew Metronome",https://www.netflix.com/watch/81415947,https://www.imdb.com/title/tt1139797,A med student with a supernatural gift tries t...,205926.0,https://occ-0-4708-64.1.nflxso.net/dnm/api/v6/...,https://m.media-amazon.com/images/M/MV5BOWM4NT...,NaN,NaN
1,HOW TO BUILD A GIRL,Comedy,"Dramas,Comedies,Films Based on Books,British",English,Movie,7.0,Canada,1-2 hour,Coky Giedroyc,Caitlin Moran,...,2021-03-04,"Film 4, Monumental Pictures, Lionsgate",https://www.netflix.com/watch/81041267,https://www.imdb.com/title/tt4193072,"When nerdy Johanna moves to London, things get...",2838.0,https://occ-0-1081-999.1.nflxso.net/dnm/api/v6...,https://m.media-amazon.com/images/M/MV5BZGUyN2...,https://www.youtube.com/watch?v=eIbcxPy4okQ,YouTube
2,Centigrade,"Drama, Thriller",Thrillers,English,Movie,6.4,Canada,1-2 hour,Brendan Walsh,"Brendan Walsh, Daley Nixon",...,2021-03-04,NaN,https://www.netflix.com/watch/81305978,https://www.imdb.com/title/tt8945942,"Trapped in a frozen car during a blizzard, a p...",1720.0,https://occ-0-1081-999.1.nflxso.net/dnm/api/v6...,https://m.media-amazon.com/images/M/MV5BODM2MD...,https://www.youtube.com/watch?v=0RvV7TNUlkQ,YouTube
3,ANNE+,Drama,"TV Dramas,Romantic TV Dramas,Dutch TV Shows",Turkish,Series,7.7,"Belgium,Netherlands",< 30 minutes,NaN,NaN,...,2021-03-04,NaN,https://www.netflix.com/watch/81336456,https://www.imdb.com/title/tt6132758,"Upon moving into a new place, a 20-something r...",1147.0,https://occ-0-1489-1490.1.nflxso.net/dnm/api/v...,https://m.media-amazon.com/images/M/MV5BNWRkMz...,NaN,NaN
4,Moxie,"Animation, Short, Drama","Social Issue Dramas,Teen Movies,Dramas,Comedie...",English,Movie,8.1,"Lithuania,Poland,France,Iceland,Italy,Spain,Gr...",1-2 hour,Stephen Irwin,NaN,...,2021-03-04,NaN,https://www.netflix.com/watch/81078393,https://www.imdb.com/title/tt2023611,Inspired by her moms rebellious past and a con...,63.0,https://occ-0-4039-1500.1.nflxso.net/dnm/api/v...,https://m.media-amazon.com/images/M/MV5BODYyNW...,NaN,NaN

In [63]:
#Deleting unnecessary columns
columns_to_drop=["Title","Tags","Hidden Gem Score","Country Availability","Director","Writer","Actors","Rotten Tomatoes Score","View Rating","Metacritic Score","Awards Nominated For","Boxoffice","Netflix Release Date","Production House","Netflix Link","IMDb Link","Summary","IMDb Votes","Image","Poster","TMDb Trailer","Trailer Site","Languages","Genre","Runtime"]
df.drop(columns_to_drop, axis=1, inplace=True)

In [64]:
#Data preview 
df.head()

  Series or Movie  IMDb Score  Awards Received Release Date
0          Series         7.9             74.0  12 Dec 2008
1           Movie         5.8              1.0  08 May 2020
2           Movie         4.3              NaN  28 Aug 2020
3          Series         6.5              1.0  01 Oct 2016
4           Movie         6.3              NaN  22 Sep 2011

In [65]:
#Null value
null_counts = df.isnull().sum()
null_dict = null_counts.to_dict()
null_dict

{'Series or Movie': 0,
 'IMDb Score': 2099,
 'Awards Received': 9405,
 'Release Date': 2107}

In [66]:
#None Null values
non_null_counts = df.notnull().sum()
non_null_dict = non_null_counts.to_dict()
non_null_dict

{'Series or Movie': 15480,
 'IMDb Score': 13381,
 'Awards Received': 6075,
 'Release Date': 13373}

In [67]:
#checking whats the percentage of null value out of my data
percentage_of_null={key: (null_dict[key] / non_null_dict[key])*100 for key in null_dict}
percentage_of_null

{'Series or Movie': 0.0,
 'IMDb Score': 15.686421044764964,
 'Awards Received': 154.8148148148148,
 'Release Date': 15.755627009646304}

In [68]:
#I am removing all rows with release date that is null.
df.dropna(subset=['Release Date'], how="any", inplace=True)

In [69]:
#I am removing all rows with IMDb Score that is null.
df.dropna(subset=['IMDb Score'], how="any", inplace=True)

In [70]:
#replace Awards Received nulls by "Not Awarded"
df['Awards Received'].fillna("Not Awarded", inplace=True)

C:\Users\saadk\AppData\Local\Temp\ipykernel_5324\2776853959.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Awards Received'].fillna("Not Awarded", inplace=True)
C:\Users\saadk\AppData\Local\Temp\ipykernel_5324\2776853959.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Not Awarded' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['Awards Received'].fillna("Not Awarded", inplace=True)

In [71]:
#change the format type of column "Release Date" to dates format
df["Release Date"]=pd.to_datetime(df["Release Date"])

In [75]:
df

      Series or Movie  IMDb Score Awards Received Release Date
0              Series         7.9            74.0   2008-12-12
1               Movie         5.8             1.0   2020-05-08
2               Movie         4.3     Not Awarded   2020-08-28
3              Series         6.5             1.0   2016-10-01
4               Movie         6.3     Not Awarded   2011-09-22
...               ...         ...             ...          ...
15464           Movie         6.5     Not Awarded   2009-02-18
15465           Movie         6.2     Not Awarded   2004-04-23
15466           Movie         6.2             1.0   2010-01-22
15467           Movie         7.3     Not Awarded   1988-09-17
15473           Movie         7.8     Not Awarded   2012-01-13

[13063 rows x 4 columns]

In [80]:
#splitting the release dates into 20 years period
years_per_category = 20
min_year = 1910
max_year = 2022
num_categories = (max_year - min_year) // years_per_category + 1
category_bins = [(min_year + i * years_per_category, min_year + (i + 1) * years_per_category - 1) for i in range(num_categories)]
labels = [f'{start}-{end}' for start, end in category_bins]
df['Release Period'] = pd.cut(df['Release Date'].dt.year, bins=[start for start, end in category_bins] + [max_year + 1], labels=labels, right=False)

      Series or Movie  IMDb Score Awards Received Release Date Release Period
0              Series         7.9            74.0   2008-12-12      1990-2009
1               Movie         5.8             1.0   2020-05-08      2010-2029
2               Movie         4.3     Not Awarded   2020-08-28      2010-2029
3              Series         6.5             1.0   2016-10-01      2010-2029
4               Movie         6.3     Not Awarded   2011-09-22      2010-2029
...               ...         ...             ...          ...            ...
15464           Movie         6.5     Not Awarded   2009-02-18      1990-2009
15465           Movie         6.2     Not Awarded   2004-04-23      1990-2009
15466           Movie         6.2             1.0   2010-01-22      2010-2029
15467           Movie         7.3     Not Awarded   1988-09-17      1970-1989
15473           Movie         7.8     Not Awarded   2012-01-13      2010-2029

[13063 rows x 5 columns]

In [111]:
df.to_csv('output.csv', index=True)